apiVersion: v1
kind: Pod
metadata:
  labels:
    run: debian
  name: debian
spec:
  nodeSelector:
    allow-stat-test: "True"
  containers:
  - image: debian
    name: debian
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "sleep infinity ;" ]
  restartPolicy: Never
